---
esphome:
  name: fineoffset-example
  friendly_name: FineOffset Example

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: components

fineoffset:
  - name: FineOffset Radio
    id: fineoffset_radio
    pin: GPIO33

sensor:
  - platform: fineoffset
    fineoffset_id: fineoffset_radio
    sensor_no: 77
    temperature:
      name: Deck Temperature
    humidity:
      name: Deck Humidity

  - platform: fineoffset
    fineoffset_id: fineoffset_radio
    sensor_no: 23
    temperature:
      name: Temperature
    humidity:
      name: Humidity

text_sensor:
  - platform: fineoffset
    name: Last Sensor Data
    type: last

  - platform: fineoffset
    name: Bad Sensor Data (CRC failed)
    type: last_bad
